version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zoho_accounts
      MYSQL_USER: zoho
      MYSQL_PASSWORD: zoho
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - shared_data:/shared

  flask_app:
    build: ./app
    container_name: flask_app
    restart: always
    environment:
      - FLASK_ENV=development
      - DB_HOST=mysql
      - DB_USER=zoho
      - DB_PASSWORD=zoho
      - DB_NAME=zoho_accounts
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - shared_data:/shared

volumes:
  mysql_data:
  shared_data:
